const dummyCustomer = {
  id: 23750,
  name: "MINI MOJOGEDANG",
  alias: null,
  owner: null,
  phone: null,
  npwp: null,
  ktp: null,
  channel: "WS",
  customer_number: "SLOWS00009",
  cust_account_id: 218050,
  bill_to_location: "MINI MOJOGEDANG",
  ship_to_location: "MINI MOJOGEDANG",
  order_type_name: "",
  order_type_id: "",
  return_order_type_name: "",
  return_order_type_id: "",
  site_type: "ROKOK",
  bill_to_site_use_id: 222060,
  ship_to_site_use_id: 222061,
  credit_checking: "Y",
  credit_exposure: "0",
  overall_credit_limit: "0",
  trx_credit_limit: "0",
  term_name: "Tunai",
  term_id: 1000,
  term_day: 0,
  price_list_name: "PL - WS / NKA",
  price_list_id: 7011,
  organization_code: "SLO",
  organization_name: "SOLO",
  organization_id: 276,
  org_name: "NNA_SLO_OU",
  org_id: "226",
  route_id: null,
  is_active: true,
  created_by: "admin",
  created_at: "2025-05-05T16:40:41.270Z",
  updated_by: "admin",
  updated_at: "2025-05-05T16:40:41.270Z",
  deleted_at: null,
  addresses: [
    {
      id: 23750,
      customer_id: 23750,
      address1:
        "GAMBARWI RT 001 RW 006 KEL SEWUREJO KEC MOJOGEDANG KARANGANYAR JAWA TENGAH",
      provinsi: "JAWA TENGAH",
      kab_kodya: "KAB KARANGANYAR",
      kecamatan: "MOJOGEDANG",
      kelurahan: "SEWUREJO",
      kodepos: null,
      is_active: true,
      created_by: "admin",
      created_at: "2025-05-05T16:40:41.270Z",
      updated_by: "admin",
      updated_at: "2025-05-05T16:40:41.270Z",
    },
  ],
};

export default dummyCustomer;
